version: '3.9'

services:
  events-store:
    container_name: ${CONTAINER_NAME}
    image: ${BROKER_HOST}:${BROKER_VERSION}
    ports:
      - ${BROKER_PORT_SERVICE}:${BROKER_PORT_SERVICE}
      - ${BROKER_PORT_MANAGEMENT}:${BROKER_PORT_MANAGEMENT}
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_DEFAULT_PASS}
    command: rabbitmq-server --heartbeat=0 # Only for debugging. Remove this line in production      
    networks:
      - zuidui

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${PGADMIN_IMAGE_NAME}:${PGADMIN_IMAGE_VERSION}
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - zuidui
      
networks:
  zuidui:
    driver: bridge
